### ISSUE TITLE
[BUG] Console Error when an attack roll is made using this and Midi-QOL

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-combat-details#33]
v11 of Foundry, 11.01 of MCD, 11.0.0 of Midi

I get the following error message when I have one token attack another token:

monks-combat-details.js:423 Uncaught (in promise) TypeError: undefined. Cannot read properties of null (reading 'disposition')
[Detected 2 packages: monks-combat-details, midi-qol]
    at MonksCombatDetails.AutoDefeated (monks-combat-details.js:423:89)
    at Object.fn (monks-combat-details.js:610:24)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at #preUpdateDocumentArray (foundry.js:13606:44)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:13383:22)
    at async Actor5e.updateDocuments (commons.js:7892:23)
    at async Actor5e.update (commons.js:7989:23)
    at async Promise.allSettled (index 0)
    at async createGMReverseDamageCard (GMAction.js:484:18)
    at async Object.createReverseDamageCard (GMAction.js:308:7)
    at async timedAwaitExecuteAsGM (GMAction.js:70:10)
    at async applyTokenDamageMany (utils.js:760:25)
    at async processDamageRoll (utils.js:903:19)
    at async Workflow._next (workflow.js:679:6)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)
    at async Workflow.next (workflow.js:248:10)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
